local BASE_WIDTH = sys.get_config_int("display.width")
local BASE_HEIGHT = sys.get_config_int("display.height")
local ZOOM

local game_events = require("management.game_events")

local function update_camera(width, height)
	local scale = math.min(width / BASE_WIDTH, height / BASE_HEIGHT)
	go.set("#camera", "orthographic_zoom", ZOOM * scale)
end

function init(self)
	ZOOM = camera.get_orthographic_zoom("#camera")

	game_events.window_resized:subscribe(update_camera, width, height)
end